---
title: "Environmental Stringency"
author: "Maya Barron"
date: "2023-04-27"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, warning = FALSE, include = FALSE}
# imports
library(tidyverse)
library(readxl)
library(plotly)
library(ggridges)
library(patchwork)
theme_set(theme_bw())
```

```{r, message = FALSE}
# datasets
emissions = read_csv("https://raw.githubusercontent.com/mrbarron3/group_project/main/data.csv")

emissions = emissions %>%
  group_by(Country) %>%
  mutate(avg_epsv = mean(Environmental_Policy_Stringency_Value)) %>%
  ungroup() %>%
  mutate(total_avg_epsv = median(avg_epsv)) %>%
  arrange(desc(avg_epsv), Year)

emissions_top = emissions %>%
  filter(avg_epsv > total_avg_epsv)

emissions_bottom = emissions %>%
  filter(avg_epsv <= total_avg_epsv)

emissions_groups = emissions %>%
  group_by(Country) %>%
  count()

emissions_diff = emissions %>%
  group_by(Country) %>%
  mutate(year_max = max(Year), year_min = min(Year)) %>%
  filter((Year == year_max | Year == year_min) & (Year == 2020 | Year == 1990)) %>%
  mutate(Year = as.character(Year)) %>%
  select(Country, Year, Environmental_Policy_Stringency_Value) %>%
  pivot_wider(names_from = Year, values_from = Environmental_Policy_Stringency_Value) %>%
  mutate(diff = `2020` - `1990`) %>%
  drop_na()

emi_90_20 = emissions_diff %>%
  pivot_longer(c("2020", "1990"), names_to = "Year", values_to = "epsi")
```

```{r}
# double bar plot
a = ggplot(emi_90_20) +
  geom_col(aes(x = reorder(Country, diff), y = epsi, fill = Year), width = 0.7, position = "dodge") + 
  scale_fill_manual(values = c("#D95F02", "#1B9E77")) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
  scale_y_continuous(expand = c(0, 0, 0.03, 0.03)) +
  labs(x = "", y = "EPS Index", title = "Environmental Policy Stringency (EPS) Index by Country and Year", subtitle = "Only Includes Countries Where Both 2020 and 1990 Data is Available")
```

```{r}
# bar plot with differences between newest and oldest data
b = ggplot(emissions_diff) +
  geom_col(aes(x = reorder(Country, diff), y = diff), fill = "#7570B3") +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
  labs(x = "Country", y = "Increase Amount", title = "Increase Between 1990 and 2020 EPS Indexes") +
  scale_y_continuous(expand = c(0, 0, 0.03, 0.03))
```

```{r, fig.height = 7}
# combined plot
a / b
```